#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>


constexpr static const uint32_t MAX_I2C_FREQ = 1000000;

extern "C" {

int main();

} // extern "C"
